import React from 'react'
import Head from 'next'
import Navbar from './Navbar'

const Layout = ({children}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        {children}
      </main>
    </div>
  )
}

export default Layout